# Generated by Django 4.1.3 on 2023-04-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port_home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
